spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/e_commerce_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

kafka:
  bootstrap-servers: kafka:9093

logging:
  level:
    root: DEBUG