spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/e_commerce_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    clear-checksums: true  # ใช้เฉพาะตอนพัฒนา

  jpa:
    hibernate:
      ddl-auto: none

kafka:
  bootstrap-servers: kafka:9093