version: '3.8'
services:
  eureka-server:
    build: ./eurekaserver-service
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    external: true


