version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - ecommerce-net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - ecommerce-net

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: e_commerce_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecommerce-net

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8085:8080"  # เปิดบนเครื่องที่พอร์ต 8085
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    networks:
      - ecommerce-net

volumes:
  pgdata:

networks:
  ecommerce-net:
    external: true