version: '3.8'
services:
  order-service:
    build: ../services/order-service
    ports:
      - "8081:8081"
    networks:
      - ecommerce-net

  inventory-service:
    build: ../services/inventory-service
    deploy:
      replicas: 1  # รัน 3  instance ไปเล๊ยยยย
    networks:
      - ecommerce-net

  # ...services อื่นๆ เหมือนกัน เพิ่ม networks: ecommerce-net เช่นกัน

networks:
  ecommerce-net:
    external: true