server:
  port: 8888

spring:
  application:
    name: order-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/app/config-repo