FROM jenkins/jenkins:lts

USER root

# ติดตั้ง docker CLI
RUN apt-get update && apt-get install -y docker.io curl

# ติดตั้ง docker compose CLI V2
RUN curl -SL https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-linux-aarch64 -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

USER jenkins