spring:
  application:
    name: order-service

  config:
    import: "configserver:http://config-server:8888"

  profiles:
    active: default

  level:
    com.zaxxer.hikari: WARN
    root: INFO
    org.apache.kafka: WARN
    org.apache.camel: WARN
    org.springframework.web: WARN
    org.apache.hc.client5.http: WARN
    com.netflix: WARN
    org.hibernate: WARN
    org.postgresql: WARN
    com.ecommerce: DEBUG
